Dev
ZzhangFun/hacker-news pull request #1
Opened 2022-07-24 10:48 UTC by ZzhangFun

Я не доволен крч, фигню написал как мне кажется.

2022-07-24 11:08 UTC, crutch12 commented
отдал @stilwuc

2022-07-27 08:54 UTC, Stilwuc commented
@ZzhangFun Можешь на codesandbox выложить плз?
лень пулить и собирать)

2022-07-28 16:18 UTC, Stilwuc requested changes

2022-07-28 16:18 UTC, Stilwuc commented on client/src/components/NewsItem.tsx
> +          Date: {time.getDate()}.{`0${time.getMonth() + 1}`}.
А если getMonth вернет 12, то будет 012?)

2022-07-28 16:18 UTC, Stilwuc commented on client/src/components/Comment.tsx
> +  const [visible, setVisible] = useState<boolean>(true);
explicit тут необязательно задавать, ts и так поймет
```suggestion
  const [visible, setVisible] = useState(true);
```

2022-07-28 16:20 UTC, Stilwuc commented
А так вообщем неплохо 👍

2022-07-28 19:44 UTC, ZzhangFun commented on client/src/components/UI/Back/Back.tsx
> +export default Back;
Знал, что это ошибка, будем считать, что это проверка на внимательность была. (На самом деле прост не хотел называть так "<BackToNews />"

2022-07-28 19:46 UTC, ZzhangFun commented on client/src/components/UI/Back/Back.module.css
> +
Странно, я вообще всё с eslint'ом пишу, странно что он не пофиксил сам, я крч презапуск потом скорее всего поставлю, чтоб правил всё перед стартом.

2022-07-28 19:52 UTC, ZzhangFun commented on client/src/components/Comments.tsx
> +  comments: INewsId[];
Хз, привычка с шарпа.
Я её сюда перетащил, когда у меня есть глобальные инты, типо IUser, ITodo и тд

2022-07-28 19:57 UTC, ZzhangFun commented on client/src/components/UI/Back/Back.tsx
> +export default Back;
Знал, что это ошибка, будем считать, что это была проверка на внимательность :D  (На самом деле не хотел прост называть так "```BackToNew```"

2022-07-28 19:58 UTC, ZzhangFun commented on client/src/components/Comment.tsx
> +  const [visible, setVisible] = useState<boolean>(true);
Та в курсе, скорее дело привычки, поэтому написал, надо избавляться.

2022-07-28 19:59 UTC, ZzhangFun commented on client/src/components/NewsItem.tsx
> +          Date: {time.getDate()}.{`0${time.getMonth() + 1}`}.
Да, чушь какая-то)

2022-07-28 20:00 UTC, ZzhangFun commented on client/src/components/UI/AppRouter.tsx
> +      {routes.map((route) => (
Вообще, я так учился у сеньёра по видосам, в любом случае учту, хотя выглядит как лесенка кнш.

2022-07-29 07:12 UTC, Stilwuc commented on client/src/components/Comments.tsx
> +  comments: INewsId[];
Понимаю, сам на c# также писал)
Но тут в ТС, такое не рекомендуется
![image](https://user-images.githubusercontent.com/44724024/181703592-0eec52cd-b997-413d-ba09-eb570409802f.png)

2022-07-29 13:26 UTC, crutch12 commented on client/src/components/Comments.tsx
> +  comments: INewsId[];
Можно сурс?

2022-07-29 17:44 UTC, Stilwuc commented on client/src/components/Comments.tsx
> +  comments: INewsId[];
Для тебя все что хочешь.
Конкретно скрин выше отсюда 
https://stackoverflow.com/questions/31876947/confused-about-the-interface-and-class-coding-guidelines-for-typescript#:~:text=Typescript%20handbook%20still%20says%3A%20In,but%20looks%20like%20strong%20recommendation.
Но вот еще полезный тред с обсуждениями
https://github.com/microsoft/TypeScript-Handbook/issues/121

2022-07-30 15:31 UTC, ZzhangFun commented
Название коммита кнш кал, но решил всё одним залить, не думая :)
В общем, вроде всё кроме ```styled-comp``` сделал, хотел и ```styled``` сделать, но меня на баскет позвали, так что пока что вот.
Если захочешь, сделаю всё.
Если там песок не обновился, то вечером обновлю, когда приду.
Можно смотреть.

2022-07-30 15:41 UTC, Stilwuc commented
> Название коммита кнш кал, но решил всё одним залить, не думая :) В общем, вроде всё кроме `styled-comp` сделал, хотел и `styled` сделать, но меня на баскет позвали, так что пока что вот. Если захочешь, сделаю всё. Если там песок не обновился, то вечером обновлю, когда приду. Можно смотреть.

Да забьем наверно пока на styled. css модули приемлимо)
В будущем просто советую сразу в нем писать, более распростроненное решение
А так гуд, гляну завтра

2022-08-01 14:47 UTC, Stilwuc approved these changes
Шик, можешь мержить

2022-08-01 14:47 UTC, Stilwuc commented on client/src/components/UI/Navbar/Navbar.module.css
> +    height: 5vmax;
Лучше статику зарядить, а то расширяющийся хедер выглядит необычно)
![image](https://user-images.githubusercontent.com/44724024/182175992-94999be3-84aa-42b1-92b5-e1685d6a3d61.png)
![image](https://user-images.githubusercontent.com/44724024/182175924-5f02b3ff-9c42-45c6-b108-e855414247cf.png)

2022-08-01 14:47 UTC, Stilwuc commented on client/src/pages/News.tsx
> +      {news && news.map((n) => <NewsItem key={n.id} news={n} />)};
Переменные из одной буквы лучше не стоит называть, а то не смотря контекст сам потом не поймешь что такое `n`

2022-08-02 08:45 UTC, merged